type CartaService = {
  id: string;
  title: string;
  category: string;
  audienceId: string;
  audienceIds: string[];
  department: string;
  destination: string;
  url: string;
  initials: string;
  searchTerms?: string[];
};

export const cartaServiceDestination = "Portal de Serviços de Amargosa";

export const cartaServiceLinks: Record<string, string> = {
  "1doc-abastecimento-de-agua": "https://acesso.amargosa.ba.gov.br/abastecimento-agua",
  "1doc-alteracao-do-cadastro-economico": "https://acesso.amargosa.ba.gov.br/cadastro-alteracao",
  "1doc-alvara-de-funcionamento": "https://acesso.amargosa.ba.gov.br/alvara-funcionamento",
  "1doc-alvara-de-obras-construcao-ampliacao-reforma-e-demolicao": "https://acesso.amargosa.ba.gov.br/alvara-obras",
  "1doc-alvara-sanitario": "https://acesso.amargosa.ba.gov.br/alvara-sanitario",
  "1doc-alvara-temporario-para-parque-de-diversoes-e-circo": "https://acesso.amargosa.ba.gov.br/alvara-temporario",
  "1doc-atestado-medico-licenca-tratamento-de-saude": "https://acesso.amargosa.ba.gov.br/licenca-atestado",
  "1doc-atualizacao-de-cadastro-funcional": "https://acesso.amargosa.ba.gov.br/atualizacao-cadastral",
  "1doc-autorizacao-para-eventos-em-espaco-publico": "https://acesso.amargosa.ba.gov.br/autorizacao-eventos",
  "1doc-averbacao-de-imoveis": "https://acesso.amargosa.ba.gov.br/averbacao-imoveis",
  "1doc-baixa-do-cadastro-de-inscricao-municipal": "https://acesso.amargosa.ba.gov.br/baixa-cadastro",
  "1doc-cadastramento-de-area-urbana-com-origem-rural": "https://acesso.amargosa.ba.gov.br/cadastramento-area",
  "1doc-cadastro-imobiliario": "https://acesso.amargosa.ba.gov.br/cadastro-imobiliario",
  "1doc-cancelamento-ou-baixa-de-credito-tributario": "https://acesso.amargosa.ba.gov.br/cancelamento-baixa",
  "1doc-certidao-de-1-lancamento-do-iptu": "https://acesso.amargosa.ba.gov.br/certidao-1",
  "1doc-certidao-de-comprovacao-de-endereco": "https://acesso.amargosa.ba.gov.br/certidao-comprovacao",
  "1doc-certidao-de-inscricao-municipal-empresa": "https://acesso.amargosa.ba.gov.br/certidao-inscricao",
  "1doc-certidao-de-regularidade-fiscal-empresas": "https://acesso.amargosa.ba.gov.br/certidao-regularidade",
  "1doc-certidao-de-regularidade-fiscal-iptu": "https://acesso.amargosa.ba.gov.br/certidao-regularidade-fiscal",
  "1doc-certidao-de-valor-venal-rural": "https://acesso.amargosa.ba.gov.br/certidao-valor",
  "1doc-certidao-de-valor-venal-urbano": "https://acesso.amargosa.ba.gov.br/certidao-valor-venal",
  "1doc-certidao-negativa-de-pessoa-fisica": "https://acesso.amargosa.ba.gov.br/certidao-negativa",
  "1doc-certidao-por-tempo-de-servico": "https://acesso.amargosa.ba.gov.br/certidao-tempo",
  "1doc-concurso": "https://acesso.amargosa.ba.gov.br/concurso",
  "1doc-consulta-de-debitos-e-informacoes-cadastrais": "https://acesso.amargosa.ba.gov.br/consulta-debitos",
  "1doc-contracheque": "https://acesso.amargosa.ba.gov.br/emissao-contracheque",
  "1doc-correcao-de-valores-salariais": "https://acesso.amargosa.ba.gov.br/correcao-valores",
  "1doc-credencial-de-estacionamento-para-idoso": "https://acesso.amargosa.ba.gov.br/credencial-estacionamento",
  "1doc-credencial-de-estacionamento-para-pcd": "https://acesso.amargosa.ba.gov.br/credencial-estacionamento-pcd",
  "1doc-defesa-de-autuacao-pessoa-juridica": "https://acesso.amargosa.ba.gov.br/defesa-autuacao",
  "1doc-desmembramento-de-area-rural": "https://acesso.amargosa.ba.gov.br/desmembramento-area",
  "1doc-desmembramento-de-area-urbano": "https://acesso.amargosa.ba.gov.br/desmembramento-area-urbano",
  "1doc-desmembramento-de-lotes": "https://acesso.amargosa.ba.gov.br/desmembramento-lotes",
  "1doc-dispensa-de-licenca-dl": "https://acesso.amargosa.ba.gov.br/licenca-dispensa",
  "1doc-estagio-probatorio": "https://acesso.amargosa.ba.gov.br/estagio-probatorio",
  "1doc-extincao-ou-suspensao-de-execucao-extrajudicial-ou-judicial": "https://acesso.amargosa.ba.gov.br/extincao-suspensao",
  "1doc-ferias-marcacao-e-alteracao": "https://acesso.amargosa.ba.gov.br/ferias-marcacao",
  "1doc-guia-de-sepultamento": "https://acesso.amargosa.ba.gov.br/guia-sepultamento",
  "1doc-habite-se": "https://acesso.amargosa.ba.gov.br/solicitar-habite",
  "1doc-indicacao-de-condutor-infrator-pessoa-fisica": "https://acesso.amargosa.ba.gov.br/indicacao-condutor",
  "1doc-indicacao-de-condutor-infrator-pessoa-juridica": "https://acesso.amargosa.ba.gov.br/indicacao-condutor-infrator",
  "1doc-inscricao-municipal-cadastro-economico": "https://acesso.amargosa.ba.gov.br/cadastro-inscricao",
  "1doc-interdicao-de-via": "https://acesso.amargosa.ba.gov.br/interdicao-via",
  "1doc-isencao-de-iptu": "https://acesso.amargosa.ba.gov.br/isencao-iptu",
  "1doc-isencao-de-itbi-itv": "https://acesso.amargosa.ba.gov.br/isencao-itbi",
  "1doc-isencao-de-taxas": "https://acesso.amargosa.ba.gov.br/isencao-taxas",
  "1doc-lancamento-do-issqn-habite-se": "https://acesso.amargosa.ba.gov.br/lancamento-issqn",
  "1doc-licenca-por-motivo-de-doenca-em-pessoa-da-familia": "https://acesso.amargosa.ba.gov.br/licenca-motivo",
  "1doc-licenca-premio": "https://acesso.amargosa.ba.gov.br/licenca-premio",
  "1doc-limpeza-publica": "https://acesso.amargosa.ba.gov.br/limpeza-publica",
  "1doc-numeracao-predial": "https://acesso.amargosa.ba.gov.br/numeracao-predial",
  "1doc-parcelamento-de-debito-do-iptu": "https://acesso.amargosa.ba.gov.br/parcelamento-debito",
  "1doc-pedido-de-reajuste-reequilibrio-contratual": "https://acesso.amargosa.ba.gov.br/pedido-reajuste",
  "1doc-poda-de-arvore": "https://acesso.amargosa.ba.gov.br/poda-arvore",
  "1doc-prescricao-de-credito-tributario-ou-de-renda-iptu-tll-tff": "https://acesso.amargosa.ba.gov.br/prescricao-credito",
  "1doc-progressao-na-carreira": "https://acesso.amargosa.ba.gov.br/progressao-carreira",
  "1doc-reconhecimento-de-imunidade-isencao-ou-nao-incidencia": "https://acesso.amargosa.ba.gov.br/reconhecimento-imunidade",
  "1doc-recurso-a-junta-administrativa-de-recursos-de-infracoes-cetran": "https://acesso.amargosa.ba.gov.br/recurso-junta",
  "1doc-recurso-a-junta-administrativa-de-recursos-de-infracoes-jari": "https://acesso.amargosa.ba.gov.br/recurso-junta-administrativa",
  "1doc-regularizacao-de-loteamentos": "https://acesso.amargosa.ba.gov.br/regularizacao-loteamentos",
  "1doc-regularizacao-fundiaria": "https://acesso.amargosa.ba.gov.br/regularizacao-fundiaria",
  "1doc-requerimento-escolar": "https://acesso.amargosa.ba.gov.br/requerimento-escolar",
  "1doc-ressarcimento-e-indenizacoes": "https://acesso.amargosa.ba.gov.br/ressarcimento-indenizacoes",
  "1doc-restituicao-de-tributos": "https://acesso.amargosa.ba.gov.br/restituicao-tributos",
  "1doc-retirada-de-entulhos": "https://acesso.amargosa.ba.gov.br/retirada-entulhos",
  "1doc-revisao-de-area": "https://acesso.amargosa.ba.gov.br/revisao-area",
  "1doc-revisao-de-calculo-de-iptu": "https://acesso.amargosa.ba.gov.br/revisao-calculo",
  "1doc-revisao-de-calculo-de-itiv": "https://acesso.amargosa.ba.gov.br/revisao-calculo-itiv",
  "1doc-revisao-de-calculo-de-tff": "https://acesso.amargosa.ba.gov.br/revisao-calculo-tff",
  "1doc-revisao-de-caracteristicas-imobiliaria": "https://acesso.amargosa.ba.gov.br/revisao-caracteristicas",
  "1doc-servicos-de-manutencao-publica": "https://acesso.amargosa.ba.gov.br/servicos-manutencao",
  "1doc-solicitacao-de-licenca-ambiental": "https://acesso.amargosa.ba.gov.br/licenca-solicitacao",
  "1doc-solicitacao-de-reforma-de-carneira": "https://acesso.amargosa.ba.gov.br/solicitacao-reforma",
  "1doc-solicitacao-renovacao-de-licenca-ambiental": "https://acesso.amargosa.ba.gov.br/solicitacao-renovacao-licenca",
  "1doc-solicitacoes-para-eventos-esportivos-caminhadas-carreatas-e-etc": "https://acesso.amargosa.ba.gov.br/solicitacoes-eventos",
  "1doc-transferencia-de-titularidade-imobiliaria": "https://acesso.amargosa.ba.gov.br/transferencia-titularidade",
  "1doc-transito-defesa-de-autuacao-pessoa-fisica": "https://acesso.amargosa.ba.gov.br/defesa-autuacao-pessoa",
  "1doc-troca-de-lampadas": "https://acesso.amargosa.ba.gov.br/troca-lampadas",
  "1doc-unificacao-de-lotes": "https://acesso.amargosa.ba.gov.br/unificacao-lotes",
};

export const cartaOnlyServices: CartaService[] = [
  {
    id: "carta-segunda-via-iptu",
    title: "2ª via do IPTU",
    category: "Tributos",
    audienceId: "cidadao",
    audienceIds: ["cidadao", "empresa"],
    department: "SEAFI-SUCAI - Supervisão de Cadastro Imobiliário",
    destination: cartaServiceDestination,
    url: "https://acesso.amargosa.ba.gov.br/2-via",
    initials: "2I",
  },
  {
    id: "carta-declaracao-de-matricula",
    title: "Declaração de matrícula",
    category: "Cidadão",
    audienceId: "cidadao",
    audienceIds: ["cidadao"],
    department: "SEMED-GAB - Gabinete",
    searchTerms: ["requerimento escolar", "comprovante de matrícula"],
    destination: cartaServiceDestination,
    url: "https://acesso.amargosa.ba.gov.br/declaracao-matricula",
    initials: "DM",
  },
  {
    id: "carta-emissao-de-boletim-escolar",
    title: "Emissão de boletim escolar",
    category: "Cidadão",
    audienceId: "cidadao",
    audienceIds: ["cidadao"],
    department: "SEMED-GAB - Gabinete",
    searchTerms: ["requerimento escolar", "notas escolares"],
    destination: cartaServiceDestination,
    url: "https://acesso.amargosa.ba.gov.br/emissao-boletim",
    initials: "EB",
  },
  {
    id: "carta-matricula-escolar",
    title: "Matrícula escolar",
    category: "Cidadão",
    audienceId: "cidadao",
    audienceIds: ["cidadao"],
    department: "SEMED-GAB - Gabinete",
    searchTerms: ["requerimento escolar", "inscrição escolar"],
    destination: cartaServiceDestination,
    url: "https://acesso.amargosa.ba.gov.br/matricula-escolar",
    initials: "ME",
  },
  {
    id: "carta-segunda-via-de-documentos-escolares",
    title: "Segunda via de documentos escolares",
    category: "Cidadão",
    audienceId: "cidadao",
    audienceIds: ["cidadao"],
    department: "SEMED-GAB - Gabinete",
    searchTerms: ["requerimento escolar", "documento escolar"],
    destination: cartaServiceDestination,
    url: "https://acesso.amargosa.ba.gov.br/segunda-via",
    initials: "SD",
  },
  {
    id: "carta-solicitacao-de-historico-escolar",
    title: "Solicitação de histórico escolar",
    category: "Cidadão",
    audienceId: "cidadao",
    audienceIds: ["cidadao"],
    department: "SEMED-GAB - Gabinete",
    searchTerms: ["requerimento escolar", "histórico escolar"],
    destination: cartaServiceDestination,
    url: "https://acesso.amargosa.ba.gov.br/solicitacao-historico",
    initials: "SH",
  },
];
