(() => {
  const content = window.CENTRAL_CONTENT;
  const page = content.pages[0];
  const root = document.getElementById("conteudo");
  let audience = "todos";
  let category = "todos";
  let query = "";
  const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
  const segment = (type) => page.segments.find((entry) => entry.type === type);
  const entries = (entry, type) => entry?.items.filter((item) => item.type === type) || [];
  const roleItem = (entry, role) => entry?.items.find((item) => item.role === role);
  const text = (entry, role, fallback = "") => roleItem(entry, role)?.value || fallback;
  const editorItemAttr = (item) => item?.id ? ` data-editor-item-id="${escapeHtml(item.id)}"` : "";
  const services = entries(segment("catalog"), "service");
  const audienceItems = entries(segment("audiences"), "audience");
  const style = (entry) => { const image = entry.style.backgroundImage ? `background-image:linear-gradient(#063d32c9,#063d32c9),url('${entry.style.backgroundImage}')` : ""; return `--segment-bg:${entry.style.background};--segment-color:${entry.style.color};--segment-accent:${entry.style.accent};${image}`; };
  const links = (entry) => entries(entry, "link").map((item) => `<a${editorItemAttr(item)} href="${escapeHtml(item.url)}" ${item.url.startsWith("http") ? 'target="_blank" rel="noreferrer"' : ""}>${escapeHtml(item.text)}</a>`).join("");
  const heading = (entry) => { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); return `<header><div>${eyebrow?.value ? `<span${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow.value)}</span>` : ""}<h2${editorItemAttr(title)}>${escapeHtml(title?.value || entry.name)}</h2></div>${description?.value ? `<p${editorItemAttr(description)}>${escapeHtml(description.value)}</p>` : ""}</header>`; };
  const logo = (entry) => { const image = entries(entry, "image").find((item) => item.role === "logo"); return image?.src ? `<img${editorItemAttr(image)} class="logo-image" src="${image.src}" alt="${escapeHtml(image.alt)}">` : `<span${editorItemAttr(image)} class="mark">AM</span>`; };
  const serviceCard = (service, index, featured = false, editorItem = service) => `<a${editorItemAttr(editorItem)} class="${featured ? "featured-card" : "service-card"}" href="${escapeHtml(service.url)}" target="_blank" rel="noreferrer">${featured ? `<span class="rank">${String(index + 1).padStart(2, "0")}</span>` : ""}<span><small>${escapeHtml(service.category)}</small><strong>${escapeHtml(service.title)}</strong><em>${escapeHtml(service.department)}</em></span><b>${featured ? "↗" : `${escapeHtml(service.destination)} ↗`}</b></a>`;

  function renderSegment(entry) {
    if (!entry.enabled) return "";
    const open = `<section data-editor-segment-id="${escapeHtml(entry.id)}" id="${entry.type === "catalog" ? "todos-os-servicos" : escapeHtml(entry.id)}" class="editable segment-${escapeHtml(entry.type)} variant-${escapeHtml(entry.style.variant || "institutional")} width-${escapeHtml(entry.style.width)} spacing-${escapeHtml(entry.style.spacing)} radius-${escapeHtml(entry.style.radius)}" style="${style(entry)}">`;
    if (entry.type === "utility") { const label = roleItem(entry, "label"); return `${open}<div class="utility"><span${editorItemAttr(label)}>${escapeHtml(label?.value || "")}</span><nav>${links(entry)}</nav></div></section>`; }
    if (entry.type === "header") { const brandLine = roleItem(entry, "brandLine"); const municipality = roleItem(entry, "municipality"); const subtitle = roleItem(entry, "subtitle"); return `${open}<div class="header"><a class="brand" href="#">${logo(entry)}<span><small${editorItemAttr(brandLine)}>${escapeHtml(brandLine?.value || "")}</small><strong${editorItemAttr(municipality)}>${escapeHtml(municipality?.value || "")}</strong><em${editorItemAttr(subtitle)}>${escapeHtml(subtitle?.value || "")}</em></span></a><nav>${links(entry)}</nav><span class="menu">☰ Menu</span></div></section>`; }
    if (entry.type === "hero") { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); const notice = roleItem(entry, "notice"); const search = entries(entry, "search")[0]; const refs = entries(segment("featured"), "serviceRef").slice(0, 4).map((ref) => services.find((service) => service.id === ref.serviceId)).filter(Boolean); return `${open}<div class="hero"><span${editorItemAttr(eyebrow)} class="eyebrow">${escapeHtml(eyebrow?.value || "")}</span><h1${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</h1>${description?.value ? `<p${editorItemAttr(description)}>${escapeHtml(description.value)}</p>` : ""}<label${editorItemAttr(search)} class="search"><span>⌕</span><input id="search" placeholder="${escapeHtml(search?.placeholder)}" aria-label="Buscar serviços"><a href="#todos-os-servicos">${escapeHtml(search?.buttonText || "Buscar")}</a></label><div class="popular"><span>Mais buscados:</span>${refs.map((service) => `<button type="button" data-shortcut="${escapeHtml(service.title)}">${escapeHtml(service.title)}</button>`).join("")}</div>${notice?.value ? `<small${editorItemAttr(notice)}>${escapeHtml(notice.value)}</small>` : ""}</div></section>`; }
    if (entry.type === "audiences") return `${open}<div class="audience-panel">${heading(entry)}<div class="audiences">${entries(entry, "audience").map((item) => `<button${editorItemAttr(item)} type="button" data-audience="${escapeHtml(item.id)}"><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.description)}</small><b>Ver serviços →</b></button>`).join("")}</div></div></section>`;
    if (entry.type === "featured") { const featured = entries(entry, "serviceRef").map((ref) => ({ ref, service: services.find((service) => service.id === ref.serviceId) })).filter((item) => item.service); return `${open}<div class="section">${heading(entry)}<div class="featured">${featured.map((item, index) => serviceCard(item.service, index, true, item.ref)).join("")}</div></div></section>`; }
    if (entry.type === "categories") return `${open}<div class="categories-section"><div class="boundary">${heading(entry)}<div class="categories">${entries(entry, "category").map((item) => `<button${editorItemAttr(item)} type="button" data-category="${escapeHtml(item.label)}"><span><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.description)}</small></span><b>→</b></button>`).join("")}</div></div></div></section>`;
    if (entry.type === "catalog") { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); return `${open}<div class="results section"><header><div><span${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</span><h2${editorItemAttr(title)} id="results-title">${escapeHtml(title?.value || "")}</h2></div><div><button id="clear" hidden>Limpar filtros ×</button><b id="result-count"></b></div></header><div id="service-grid" class="service-grid"></div><div id="empty" class="empty" hidden>Nenhum serviço encontrado.</div></div></section>`; }
    if (entry.type === "help") { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); return `${open}<div class="help"><div><span${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</span><h2${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</h2><p${editorItemAttr(description)}>${escapeHtml(description?.value || "")}</p></div>${links(entry)}</div></section>`; }
    if (entry.type === "footer") { const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); return `${open}<footer><div class="brand">${logo(entry)}<span><strong${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</strong><em${editorItemAttr(description)}>${escapeHtml(description?.value || "")}</em></span></div><nav>${links(entry)}</nav></footer></section>`; }
    if (entry.type === "amanda") { const avatar = entries(entry, "image").find((item) => item.role === "avatar"); const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); const status = roleItem(entry, "status"); const notice = roleItem(entry, "notice"); const avatarHtml = avatar?.src ? `<img src="${avatar.src}" alt="">` : "A"; const conversation = entries(entry, "search")[0]; return `<div data-editor-segment-id="${escapeHtml(entry.id)}" id="amanda-widget" class="amanda-widget" style="${style(entry)}"><button id="amanda-launcher" class="amanda-launcher" type="button" aria-expanded="false"><span${editorItemAttr(avatar)} class="amanda-symbol">${avatarHtml}</span><span><small${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</small><strong>Amanda</strong></span><b>✦</b></button><aside id="amanda-panel" class="amanda-panel" hidden><header><div class="amanda-identity"><span${editorItemAttr(avatar)} class="amanda-symbol">${avatarHtml}</span><span><small${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</small><strong${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</strong></span></div><button id="amanda-close" type="button">×</button></header><div class="amanda-body"><p${editorItemAttr(description)}>${escapeHtml(description?.value || "")}</p><small${editorItemAttr(status)} class="amanda-status">${escapeHtml(status?.value || "")}</small><div id="amanda-prompts" class="amanda-prompts">${entry.items.filter((item) => item.role === "prompt").map((item) => `<button${editorItemAttr(item)} type="button" data-amanda-prompt="${escapeHtml(item.value)}">${escapeHtml(item.value)} <b>↗</b></button>`).join("")}</div><div id="amanda-transcript" class="amanda-transcript"></div></div><form${editorItemAttr(conversation)} id="amanda-form"><textarea id="amanda-input" rows="2" placeholder="${escapeHtml(conversation?.placeholder)}"></textarea><button type="submit">${escapeHtml(conversation?.buttonText || "Enviar")} ↗</button></form><small${editorItemAttr(notice)} class="amanda-notice">${escapeHtml(notice?.value || "")}</small></aside></div>`; }
    return `${open}<div class="section generic">${heading(entry)}<div>${entry.items.filter((item) => !["eyebrow", "title", "description"].includes(item.role)).map((item) => item.type === "image" && item.src ? `<img${editorItemAttr(item)} src="${item.src}" alt="${escapeHtml(item.alt)}">` : item.type === "link" ? `<a${editorItemAttr(item)} href="${escapeHtml(item.url)}">${escapeHtml(item.text)}</a>` : `<p${editorItemAttr(item)}>${escapeHtml(item.value || item.label)}</p>`).join("")}</div></div></section>`;
  }

  root.innerHTML = page.segments.map(renderSegment).join("");
  document.documentElement.style.setProperty("--green", content.site.primaryColor);
  document.documentElement.style.setProperty("--red", content.site.accentColor);

  function renderServices() {
    const normalized = query.trim().toLocaleLowerCase("pt-BR");
    const filtered = services.filter((service) => (audience === "todos" || service.audienceId === audience) && (category === "todos" || service.category === category) && (!normalized || `${service.title} ${service.department} ${service.category} ${service.destination}`.toLocaleLowerCase("pt-BR").includes(normalized)));
    document.getElementById("service-grid").innerHTML = filtered.map((service, index) => serviceCard(service, index)).join("");
    document.getElementById("result-count").textContent = `${filtered.length} encontrado${filtered.length === 1 ? "" : "s"}`;
    document.getElementById("results-title").textContent = audience !== "todos" ? `Serviços para ${audienceItems.find((item) => item.id === audience)?.label}` : category !== "todos" ? category : query ? "Resultado da busca" : text(segment("catalog"), "title", "Todos os serviços");
    document.getElementById("empty").hidden = filtered.length !== 0;
    document.getElementById("clear").hidden = audience === "todos" && category === "todos" && !query;
  }
  const scrollResults = () => document.getElementById("todos-os-servicos")?.scrollIntoView({ behavior: "smooth" });
  document.getElementById("search")?.addEventListener("input", (event) => { query = event.target.value; renderServices(); });
  document.querySelectorAll("[data-shortcut]").forEach((button) => button.addEventListener("click", () => { query = button.dataset.shortcut; document.getElementById("search").value = query; audience = "todos"; category = "todos"; renderServices(); scrollResults(); }));
  document.querySelectorAll("[data-audience]").forEach((button) => button.addEventListener("click", () => { audience = button.dataset.audience; category = "todos"; renderServices(); scrollResults(); }));
  document.querySelectorAll("[data-category]").forEach((button) => button.addEventListener("click", () => { category = button.dataset.category; audience = "todos"; renderServices(); scrollResults(); }));
  document.getElementById("clear")?.addEventListener("click", () => { audience = "todos"; category = "todos"; query = ""; document.getElementById("search").value = ""; renderServices(); });
  const amandaLauncher = document.getElementById("amanda-launcher"); const amandaPanel = document.getElementById("amanda-panel");
  const toggleAmanda = (open) => { if (!amandaPanel) return; amandaPanel.hidden = !open; amandaLauncher?.setAttribute("aria-expanded", String(open)); };
  const askAmanda = (question) => { const value = question.trim(); if (!value) return; document.getElementById("amanda-prompts").hidden = true; const transcript = document.getElementById("amanda-transcript"); transcript.insertAdjacentHTML("beforeend", `<article class="user"><small>Você</small><p>${escapeHtml(value)}</p></article><article><small>Amanda</small><p>Minha inteligência ainda está sendo preparada. Em breve vou responder e indicar o canal oficial mais adequado para você.</p></article>`); document.getElementById("amanda-input").value = ""; };
  amandaLauncher?.addEventListener("click", () => toggleAmanda(amandaPanel.hidden)); document.getElementById("amanda-close")?.addEventListener("click", () => toggleAmanda(false));
  document.querySelectorAll("[data-amanda-prompt]").forEach((button) => button.addEventListener("click", () => askAmanda(button.dataset.amandaPrompt)));
  document.getElementById("amanda-form")?.addEventListener("submit", (event) => { event.preventDefault(); askAmanda(document.getElementById("amanda-input").value); });
  document.addEventListener("keydown", (event) => { if (event.key === "Escape") toggleAmanda(false); });
  renderServices();
  const editorSelection = window.CENTRAL_EDITOR_SELECTION;
  if (editorSelection?.segmentId) {
    const selectedSegment = [...document.querySelectorAll("[data-editor-segment-id]")].find((element) => element.dataset.editorSegmentId === editorSelection.segmentId);
    selectedSegment?.classList.add("editor-selected-segment");
    const selectedItems = editorSelection.itemId ? [...document.querySelectorAll("[data-editor-item-id]")].filter((element) => element.dataset.editorItemId === editorSelection.itemId) : [];
    selectedItems.forEach((element) => element.classList.add("editor-selected-item"));
    if (selectedItems.length && selectedSegment?.id === "amanda-widget") toggleAmanda(true);
    requestAnimationFrame(() => (selectedItems.find((element) => element.offsetParent) || selectedSegment)?.scrollIntoView({ behavior: "smooth", block: "center" }));
  }
})();
