(() => {
  const content = window.CENTRAL_CONTENT;
  const siteDesign = content.site.design || { theme: "institutional", palette: "amargosa", headingFont: "lora", bodyFont: "source", fontSize: "large", hoverEffect: "none", clickEffect: "none" };
  const currentPage = content.pages[0];
  const page = content.pages.find((entry) => entry.slug === "/" || entry.id === "home") || currentPage;
  const directoryPage = content.pages.find((entry) => entry.id === "directory");
  const detailPage = content.pages.find((entry) => entry.id === "service-detail");
  const root = document.getElementById("conteudo");
  root.className = `site-root site-theme-${siteDesign.theme || "institutional"} site-palette-${siteDesign.palette || "amargosa"} site-hover-${siteDesign.hoverEffect || "none"} site-click-${siteDesign.clickEffect || "none"}`;
  let audience = "todos";
  let category = "todos";
  let query = "";
  const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
  const segment = (type) => page.segments.find((entry) => entry.type === type);
  const internalSegment = (pageEntry, type) => pageEntry?.segments.find((entry) => entry.type === type);
  const entries = (entry, type) => entry?.items.filter((item) => item.type === type) || [];
  const roleItem = (entry, role) => entry?.items.find((item) => item.role === role);
  const text = (entry, role, fallback = "") => roleItem(entry, role)?.value || fallback;
  const dimension = (value, minimum) => { const number = Math.round(Number(value)); return Number.isFinite(number) && number >= minimum ? number : null; };
  const positionStyle = (entry) => { const x = Math.round(Number(entry?.position?.x) || 0); const y = Math.round(Number(entry?.position?.y) || 0); return x || y ? `position:relative;z-index:2;transform:translate(${x}px,${y}px);` : ""; };
  const sizeStyle = (entry, segmentSize = false) => { const width = dimension(entry?.size?.width, segmentSize ? 160 : 40); const height = dimension(entry?.size?.height, 32); return `${width ? `width:${width}px;max-width:100%;` : ""}${height ? `min-height:${height}px;` : ""}${segmentSize ? "" : positionStyle(entry)}`; };
  const editorItemAttr = (item) => item?.id ? ` data-editor-item-id="${escapeHtml(item.id)}" data-position-x="${Math.round(Number(item.position?.x) || 0)}" data-position-y="${Math.round(Number(item.position?.y) || 0)}"${item.size ? ' data-user-sized-item="true"' : ""}${item.position ? ' data-user-positioned-item="true"' : ""}${item.size || item.position ? ` style="${sizeStyle(item)}"` : ""}` : "";
  const fontStacks = { lora: "Lora Variable,Georgia,serif", source: "Source Sans 3 Variable,Segoe UI,sans-serif", segoe: "Segoe UI,Tahoma,sans-serif", georgia: "Georgia,Times New Roman,serif", cambria: "Cambria,Georgia,serif", arial: "Arial,Helvetica,sans-serif" };
  const slugify = (value = "") => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const serviceAudiences = (service) => service.audienceIds?.length ? service.audienceIds : service.audienceId ? [service.audienceId] : [];
  const services = entries(segment("catalog"), "service");
  const audienceItems = entries(segment("audiences"), "audience");
  const visibleFlow = page.segments.filter((entry) => entry.enabled && entry.type !== "amanda");
  const mergeClasses = (entry) => { const index = visibleFlow.findIndex((candidate) => candidate.id === entry.id); if (index < 0) return ""; const previous = index > 0 && entry.mergeWithPrevious ? " merge-with-previous" : ""; const next = visibleFlow[index + 1]?.mergeWithPrevious ? " merge-with-next" : ""; return `${previous}${next}`; };
  const backgroundStyle = (entry) => entry.style.backgroundImage ? `background-image:linear-gradient(#063d32ad,#063d32ad),url('${entry.style.backgroundImage}');background-position:center;background-size:cover;` : "";
  const style = (entry) => { const headingFont = fontStacks[entry.style.headingFont || siteDesign.headingFont || "lora"]; const bodyFont = fontStacks[entry.style.bodyFont || siteDesign.bodyFont || "source"]; return `--segment-bg:${entry.style.background || content.site.surfaceColor || "#f7f7f3"};--segment-color:${entry.style.color || content.site.textColor || "#193a31"};--segment-accent:${entry.style.accent || content.site.primaryColor};--segment-heading-font:${headingFont};--segment-body-font:${bodyFont};${sizeStyle(entry, true)}${backgroundStyle(entry)}`; };
  const links = (entry) => entries(entry, "link").map((item) => `<a${editorItemAttr(item)} href="${escapeHtml(item.url)}" ${item.url.startsWith("http") ? 'target="_blank" rel="noreferrer"' : ""}>${escapeHtml(item.text)}</a>`).join("");
  const heading = (entry) => { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); return `<header><div>${eyebrow?.value ? `<span${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow.value)}</span>` : ""}<h2${editorItemAttr(title)}>${escapeHtml(title?.value || entry.name)}</h2></div>${description?.value ? `<p${editorItemAttr(description)}>${escapeHtml(description.value)}</p>` : ""}</header>`; };
  const logo = (entry) => { const image = entries(entry, "image").find((item) => item.role === "logo"); return image?.src ? `<img${editorItemAttr(image)} class="brand-image logo-image" src="${image.src}" alt="${escapeHtml(image.alt)}">` : `<span${editorItemAttr(image)} class="mark">AM</span>`; };
  const serviceCard = (service, index, featured = false, editorItem = service) => `<a${editorItemAttr(editorItem)} class="${featured ? "featured-card" : "service-card"}" href="?servico=${escapeHtml(service.slug || service.id)}">${featured ? `<span class="rank">${String(index + 1).padStart(2, "0")}</span>` : ""}<span><small>${escapeHtml(service.category)}</small><strong>${escapeHtml(service.title)}</strong><em>${escapeHtml(service.department)}</em></span><b>${featured ? "→" : "Ver serviço →"}</b></a>`;
  const heroCarousel = (entry) => { const images = (entry.style.backgroundImages || []).filter(Boolean); const sources = images.length ? images : entry.style.backgroundImage ? [entry.style.backgroundImage] : []; return (entry.style.variant || siteDesign.theme) === "contrast" && sources.length ? `<div class="hero-carousel" aria-hidden="true">${sources.map((source, index) => `<span class="${index === 0 ? "active" : ""}" style="background-image:url('${source}')"></span>`).join("")}</div>` : ""; };

  function renderSegment(entry) {
    if (!entry.enabled) return "";
    const anchorId = entry.type === "catalog" ? "todos-os-servicos" : entry.type === "audiences" ? "publicos" : entry.type === "categories" ? "categorias" : entry.type === "featured" ? "mais-usados" : escapeHtml(entry.id);
    const open = `<section data-editor-segment-id="${escapeHtml(entry.id)}" id="${anchorId}" class="editable segment-${escapeHtml(entry.type)} variant-${escapeHtml(entry.style.variant || siteDesign.theme || "institutional")} width-${escapeHtml(entry.style.width || "contained")} spacing-${escapeHtml(entry.style.spacing || "comfortable")} radius-${escapeHtml(entry.style.radius || "soft")} text-size-${escapeHtml(entry.style.fontSize || siteDesign.fontSize || "normal")}${entry.size ? " user-sized-segment" : ""}${mergeClasses(entry)}" style="${style(entry)}">`;
    if (entry.type === "utility") { const label = roleItem(entry, "label"); return `${open}<div class="utility"><span${editorItemAttr(label)}>${escapeHtml(label?.value || "")}</span><nav aria-label="Links de acessibilidade">${links(entry)}</nav></div></section>`; }
    if (entry.type === "header") { const subtitle = roleItem(entry, "subtitle"); return `${open}<div class="header"><a class="brand" href="#conteudo" aria-label="Página inicial da Central de Serviços">${logo(entry)}<span><strong${editorItemAttr(subtitle)}>${escapeHtml(subtitle?.value || "Central de Serviços")}</strong></span></a><nav aria-label="Navegação principal">${links(entry)}<a class="accessibility-entry" href="menu/">Acessibilidade</a></nav><div class="header-actions"><a class="menu" href="#categorias">☰ Menu de serviços</a></div></div></section>`; }
    if (entry.type === "internalHeader") { const localLogo = entries(entry, "image").find((item) => item.role === "logo"); const homeLogo = entries(segment("header"), "image").find((item) => item.role === "logo"); const source = localLogo?.src ? localLogo : homeLogo; const title = roleItem(entry, "title"); const subtitle = roleItem(entry, "subtitle"); const internalLinks = entries(entry, "link").map((item) => `<a${editorItemAttr(item)} href="${item.role === "accessibility" ? "menu/" : item.role === "menu" ? "./#categorias" : "./"}">${escapeHtml(item.text)}</a>`).join(""); const brandImage = source?.src ? `<img${editorItemAttr(localLogo)} src="${source.src}" alt="${escapeHtml(source.alt || "Prefeitura de Amargosa")}">` : `<span class="internal-mark">AM</span>`; return `${open}<header class="internal-static-header"><a class="internal-static-brand" href="./">${brandImage}<span><strong${editorItemAttr(title)}>${escapeHtml(title?.value || "Município de Amargosa")}</strong><small${editorItemAttr(subtitle)}>${escapeHtml(subtitle?.value || "Central de Serviços")}</small></span></a><nav aria-label="Navegação interna">${internalLinks}</nav></header></section>`; }
    if (entry.type === "hero") { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); const notice = roleItem(entry, "notice"); const search = entries(entry, "search")[0]; const refs = entries(segment("featured"), "serviceRef").slice(0, 4).map((ref) => services.find((service) => service.id === ref.serviceId)).filter(Boolean); return `${open}<div class="hero" style="${backgroundStyle(entry)}">${heroCarousel(entry)}<span${editorItemAttr(eyebrow)} class="eyebrow">${escapeHtml(eyebrow?.value || "")}</span><h1${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</h1>${description?.value ? `<p${editorItemAttr(description)}>${escapeHtml(description.value)}</p>` : ""}<form${editorItemAttr(search)} id="service-search-form" class="search" role="search"><span aria-hidden="true">⌕</span><label class="sr-only" for="service-search">Buscar serviços</label><input id="service-search" placeholder="${escapeHtml(search?.placeholder)}"><button type="submit">${escapeHtml(search?.buttonText || "Buscar")}</button></form><div class="popular" aria-label="Serviços mais buscados"><span>Mais buscados:</span>${refs.map((service) => `<button type="button" data-shortcut="${escapeHtml(service.title)}">${escapeHtml(service.title)}</button>`).join("")}</div>${notice?.value ? `<small${editorItemAttr(notice)}>${escapeHtml(notice.value)}</small>` : ""}</div></section>`; }
    if (entry.type === "audiences") return `${open}<div class="audience-panel">${heading(entry)}<div class="audiences" role="group" aria-label="Filtrar serviços por público">${entries(entry, "audience").map((item) => `<button${editorItemAttr(item)} type="button" data-audience="${escapeHtml(item.id)}" aria-pressed="false"><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.description)}</small><b>Ver serviços →</b></button>`).join("")}</div></div></section>`;
    if (entry.type === "featured") { const featured = entries(entry, "serviceRef").map((ref) => ({ ref, service: services.find((service) => service.id === ref.serviceId) })).filter((item) => item.service); return `${open}<div class="section">${heading(entry)}<div class="featured">${featured.map((item, index) => serviceCard(item.service, index, true, item.ref)).join("")}</div></div></section>`; }
    if (entry.type === "categories") return `${open}<div class="categories-section"><div class="boundary">${heading(entry)}<div class="categories" role="group" aria-label="Filtrar serviços por categoria">${entries(entry, "category").map((item) => `<button${editorItemAttr(item)} type="button" data-category="${escapeHtml(item.label)}" aria-pressed="false"><span><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.description)}</small></span><b aria-hidden="true">→</b></button>`).join("")}</div></div></div></section>`;
    if (entry.type === "catalog") { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); return `${open.slice(0, -1)} aria-labelledby="results-title"><div class="results section"><header><div><span${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</span><h2${editorItemAttr(title)} id="results-title" tabindex="-1">${escapeHtml(title?.value || "")}</h2></div><div><button id="clear" hidden>Limpar filtros ×</button><b id="result-count" role="status" aria-live="polite" aria-atomic="true"></b></div></header><div id="service-grid" class="service-grid" aria-label="Lista de serviços"></div><div id="empty" class="empty" role="status" hidden>Nenhum serviço encontrado.</div></div></section>`; }
    if (entry.type === "help") { const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); return `${open}<div class="help"><div><span${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</span><h2${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</h2><p${editorItemAttr(description)}>${escapeHtml(description?.value || "")}</p></div>${links(entry)}</div></section>`; }
    if (entry.type === "footer") { const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); return `${open}<footer><div class="brand">${logo(entry)}<span><strong${editorItemAttr(title)}>${escapeHtml(title?.value || "")}</strong><em${editorItemAttr(description)}>${escapeHtml(description?.value || "")}</em></span></div><nav>${links(entry)}</nav></footer></section>`; }
    if (entry.type === "amanda") { const avatar = entries(entry, "image").find((item) => item.role === "avatar"); const eyebrow = roleItem(entry, "eyebrow"); const title = roleItem(entry, "title"); const description = roleItem(entry, "description"); const status = roleItem(entry, "status"); const notice = roleItem(entry, "notice"); const avatarHtml = avatar?.src ? `<img src="${avatar.src}" alt="">` : "A"; const conversation = entries(entry, "search")[0]; return `<div data-editor-segment-id="${escapeHtml(entry.id)}" id="amanda-widget" class="amanda-widget editable segment-amanda variant-${escapeHtml(entry.style.variant || siteDesign.theme || "institutional")} text-size-${escapeHtml(entry.style.fontSize || siteDesign.fontSize || "normal")}" style="${style(entry)}"><button id="amanda-launcher" class="amanda-launcher" type="button" aria-expanded="false" aria-controls="amanda-panel" aria-haspopup="dialog"><span${editorItemAttr(avatar)} class="amanda-symbol" aria-hidden="true">${avatarHtml}</span><span><small${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</small><strong>Amanda</strong></span><b aria-hidden="true">✦</b></button><aside id="amanda-panel" class="amanda-panel" role="dialog" aria-modal="true" aria-labelledby="amanda-title" aria-describedby="amanda-description" hidden><header><div class="amanda-identity"><span${editorItemAttr(avatar)} class="amanda-symbol" aria-hidden="true">${avatarHtml}</span><span><small${editorItemAttr(eyebrow)}>${escapeHtml(eyebrow?.value || "")}</small><strong${editorItemAttr(title)} id="amanda-title">${escapeHtml(title?.value || "")}</strong></span></div><button id="amanda-close" type="button" aria-label="Fechar conversa com Amanda">×</button></header><div class="amanda-body"><p${editorItemAttr(description)} id="amanda-description">${escapeHtml(description?.value || "")}</p><small${editorItemAttr(status)} class="amanda-status" role="status">${escapeHtml(status?.value || "")}</small><div id="amanda-prompts" class="amanda-prompts">${entry.items.filter((item) => item.role === "prompt").map((item) => `<button${editorItemAttr(item)} type="button" data-amanda-prompt="${escapeHtml(item.value)}">${escapeHtml(item.value)} <b aria-hidden="true">↗</b></button>`).join("")}</div><div id="amanda-transcript" class="amanda-transcript" aria-live="polite" aria-relevant="additions"></div></div><form${editorItemAttr(conversation)} id="amanda-form"><label class="sr-only" for="amanda-input">Mensagem para Amanda</label><textarea id="amanda-input" rows="2" placeholder="${escapeHtml(conversation?.placeholder)}"></textarea><button type="submit">${escapeHtml(conversation?.buttonText || "Enviar")} <span aria-hidden="true">↗</span></button></form><small${editorItemAttr(notice)} class="amanda-notice">${escapeHtml(notice?.value || "")}</small></aside></div>`; }
    return `${open}<div class="section generic">${heading(entry)}<div>${entry.items.filter((item) => !["eyebrow", "title", "description"].includes(item.role)).map((item) => item.type === "image" && item.src ? `<img${editorItemAttr(item)} src="${item.src}" alt="${escapeHtml(item.alt)}">` : item.type === "link" ? `<a${editorItemAttr(item)} href="${escapeHtml(item.url)}">${escapeHtml(item.text)}</a>` : `<p${editorItemAttr(item)}>${escapeHtml(item.value || item.label)}</p>`).join("")}</div></div></section>`;
  }

  const routeParams = new URLSearchParams(location.search);
  const routeAudience = routeParams.get("publico") || (currentPage.id === "directory" ? "cidadao" : "");
  const routeCategory = routeParams.get("categoria");
  const routeService = routeParams.get("servico") || (currentPage.id === "service-detail" ? "isencao-de-iptu" : "");
  const categoryItems = entries(segment("categories"), "category");
  const audienceTags = (service) => `<span class="internal-static-tags">${serviceAudiences(service).map((id) => `<b>${escapeHtml(audienceItems.find((entry) => entry.id === id)?.label || id)}</b>`).join("")}</span>`;
  const internalText = (entry, role, fallback) => roleItem(entry, role)?.value || fallback;
  const internalClasses = (entry, base) => `${base} editable segment-${escapeHtml(entry?.type || "generic")} variant-${escapeHtml(entry?.style?.variant || siteDesign.theme || "institutional")} width-${escapeHtml(entry?.style?.width || "contained")} spacing-${escapeHtml(entry?.style?.spacing || "comfortable")} radius-${escapeHtml(entry?.style?.radius || "square")} text-size-${escapeHtml(entry?.style?.fontSize || siteDesign.fontSize || "normal")}`;
  const internalAttrs = (entry, base) => `data-editor-segment-id="${escapeHtml(entry?.id || "")}" class="${internalClasses(entry, base)}" style="${entry ? style(entry) : ""}"`;
  const internalShell = (body, pageEntry) => `${renderSegment(internalSegment(pageEntry, "internalHeader"))}${body}${renderSegment(segment("footer"))}`;
  function renderInternalDirectory() {
    const intro = internalSegment(directoryPage, "internalHero");
    const searchPanel = internalSegment(directoryPage, "contextualSearch");
    const catalogPanel = internalSegment(directoryPage, "internalCatalog");
    const searchItem = entries(searchPanel, "search")[0];
    const selectedAudience = audienceItems.find((entry) => entry.id === routeAudience);
    const selectedCategory = categoryItems.find((entry) => slugify(entry.label) === routeCategory || entry.id === routeCategory);
    const filtered = services.filter((service) => (!selectedAudience || serviceAudiences(service).includes(selectedAudience.id)) && (!selectedCategory || service.category === selectedCategory.label));
    const departments = [...new Set(services.map((service) => service.department))].sort((a, b) => a.localeCompare(b, "pt-BR"));
    const initials = [...new Set(services.map((service) => service.title.trim().charAt(0).toLocaleUpperCase("pt-BR")))].sort((a, b) => a.localeCompare(b, "pt-BR"));
    const cards = filtered.map((service) => `<a class="internal-static-card" data-title="${escapeHtml(`${service.title} ${service.category} ${service.department}`.toLocaleLowerCase("pt-BR"))}" data-category="${escapeHtml(service.category)}" data-audiences="${escapeHtml(serviceAudiences(service).join(" "))}" data-department="${escapeHtml(service.department)}" data-initial="${escapeHtml(service.title.trim().charAt(0).toLocaleUpperCase("pt-BR"))}" href="?servico=${escapeHtml(service.slug || service.id)}"><i aria-hidden="true">+</i><span><small>${escapeHtml(service.category)}</small><strong>${escapeHtml(service.title)}</strong><em>${escapeHtml(service.department)}</em>${audienceTags(service)}</span><b${editorItemAttr(roleItem(catalogPanel, "action"))}>${escapeHtml(internalText(catalogPanel, "action", "Acessar →"))}</b></a>`).join("");
    const categoryFilter = `<label>Categoria<select id="internal-category"><option value="todos">Todas</option>${categoryItems.map((entry) => `<option value="${escapeHtml(entry.label)}"${selectedCategory?.label === entry.label ? " selected" : ""}>${escapeHtml(entry.label)}</option>`).join("")}</select></label>`;
    const audienceFilter = `<label>Público<select id="internal-audience"><option value="todos">Todos</option>${audienceItems.map((entry) => `<option value="${escapeHtml(entry.id)}"${selectedAudience?.id === entry.id ? " selected" : ""}>${escapeHtml(entry.label)}</option>`).join("")}</select></label>`;
    const departmentFilter = `<label>Órgão responsável<select id="internal-department"><option value="todos">Todos</option>${departments.map((entry) => `<option value="${escapeHtml(entry)}">${escapeHtml(entry)}</option>`).join("")}</select></label>`;
    const initialFilter = `<label>Inicial (A–Z)<select id="internal-initial"><option value="todos">Todas</option>${initials.map((entry) => `<option>${escapeHtml(entry)}</option>`).join("")}</select></label>`;
    return internalShell(`<section ${internalAttrs(intro, "internal-static-heading")}><nav><a href="./">Início</a><span>›</span><strong>${escapeHtml(selectedAudience?.label || selectedCategory?.label || "Serviços")}</strong></nav><h1${editorItemAttr(roleItem(intro, "title"))}>${escapeHtml(internalText(intro, "title", "Central de serviços"))}</h1></section><section ${internalAttrs(searchPanel, "internal-static-search")}><header class="internal-static-selection"><div><strong>${escapeHtml(selectedAudience?.label || selectedCategory?.label || "Todos os serviços")}</strong><span>${filtered.length} serviços</span></div></header><div class="internal-static-filter-grid"><label>Buscar por serviço<input${editorItemAttr(searchItem)} id="internal-query" placeholder="${escapeHtml(searchItem?.placeholder || "Digite para buscar")}"></label>${categoryFilter}${audienceFilter}${departmentFilter}${initialFilter}<button id="internal-clear" type="button">${escapeHtml(searchItem?.buttonText || "Limpar filtros")}</button></div></section><section ${internalAttrs(catalogPanel, "internal-static-results")}><header><p>Exibindo <strong id="internal-count">${filtered.length}</strong> resultados</p><b>${escapeHtml(selectedAudience?.label || selectedCategory?.label || "Serviços")}</b></header><div id="internal-grid">${cards}</div><p${editorItemAttr(roleItem(catalogPanel, "empty"))} id="internal-empty" hidden>${escapeHtml(internalText(catalogPanel, "empty", "Nenhum serviço corresponde aos filtros escolhidos."))}</p></section>`, directoryPage);
  }
  function renderInternalService() {
    const heroPanel = internalSegment(detailPage, "serviceHero");
    const contentPanel = internalSegment(detailPage, "serviceContent");
    const service = services.find((entry) => (entry.slug || entry.id) === routeService);
    if (!service) return internalShell(`<section class="internal-static-results"><h1>Serviço não encontrado</h1><a href="./">Voltar para a Central</a></section>`, detailPage);
    const firstAudience = audienceItems.find((entry) => entry.id === serviceAudiences(service)[0]);
    const documents = service.documents?.length ? `<ul>${service.documents.map((entry) => `<li>${escapeHtml(entry)}</li>`).join("")}</ul>` : "<p>A relação oficial de documentos ainda será confirmada pelo órgão responsável.</p>";
    const steps = service.steps?.length ? `<ol>${service.steps.map((entry) => `<li>${escapeHtml(entry)}</li>`).join("")}</ol>` : "<ol><li>Confira os critérios e documentos.</li><li>Acesse o canal oficial.</li><li>Acompanhe a solicitação no sistema responsável.</li></ol>";
    return internalShell(`<article ${internalAttrs(heroPanel, "internal-static-detail")}><nav><a href="./">Início</a><span>›</span>${firstAudience ? `<a href="?publico=${escapeHtml(firstAudience.id)}">${escapeHtml(firstAudience.label)}</a><span>›</span>` : ""}<a href="?categoria=${slugify(service.category)}">${escapeHtml(service.category)}</a><span>›</span><strong>${escapeHtml(service.title)}</strong></nav><header><div><small${editorItemAttr(roleItem(heroPanel, "eyebrow"))}>${escapeHtml(internalText(heroPanel, "eyebrow", service.category))}</small><h1>${escapeHtml(service.title)}</h1><p>${escapeHtml(service.summary || `Consulte as orientações para ${service.title.toLocaleLowerCase("pt-BR")}.`)}</p>${audienceTags(service)}</div><aside><span${editorItemAttr(roleItem(heroPanel, "responsibleLabel"))}>${escapeHtml(internalText(heroPanel, "responsibleLabel", "Órgão responsável"))}</span><strong>${escapeHtml(service.department)}</strong><a${editorItemAttr(roleItem(heroPanel, "action"))} href="${escapeHtml(service.url)}" target="_blank" rel="noreferrer">${escapeHtml(service.destination || internalText(heroPanel, "action", "Acessar canal oficial"))} ↗</a></aside></header><div ${internalAttrs(contentPanel, "internal-static-copy")}><section><h2${editorItemAttr(roleItem(contentPanel, "aboutTitle"))}>${escapeHtml(internalText(contentPanel, "aboutTitle", "O que é"))}</h2><p>${escapeHtml(service.summary || "Página explicativa do serviço municipal.")}</p></section><section><h2${editorItemAttr(roleItem(contentPanel, "eligibilityTitle"))}>${escapeHtml(internalText(contentPanel, "eligibilityTitle", "Quem pode solicitar"))}</h2><p>${escapeHtml(service.eligibility || "Os critérios devem ser confirmados com o órgão responsável.")}</p></section><section><h2${editorItemAttr(roleItem(contentPanel, "documentsTitle"))}>${escapeHtml(internalText(contentPanel, "documentsTitle", "Documentos necessários"))}</h2>${documents}</section><section><h2${editorItemAttr(roleItem(contentPanel, "stepsTitle"))}>${escapeHtml(internalText(contentPanel, "stepsTitle", "Como fazer"))}</h2>${steps}</section><section class="internal-static-facts"><div><span${editorItemAttr(roleItem(contentPanel, "costLabel"))}>${escapeHtml(internalText(contentPanel, "costLabel", "Quanto custa"))}</span><strong>${escapeHtml(service.cost || "A confirmar")}</strong></div><div><span${editorItemAttr(roleItem(contentPanel, "durationLabel"))}>${escapeHtml(internalText(contentPanel, "durationLabel", "Quanto tempo leva"))}</span><strong>${escapeHtml(service.duration || "A confirmar")}</strong></div></section></div></article>`, detailPage);
  }
  if (routeAudience || routeCategory || routeService) {
    root.innerHTML = routeService ? renderInternalService() : renderInternalDirectory();
    document.documentElement.style.setProperty("--green", content.site.primaryColor); document.documentElement.style.setProperty("--red", content.site.accentColor); document.documentElement.style.setProperty("--deep", content.site.deepColor || "#04392d"); document.documentElement.style.setProperty("--cream", content.site.surfaceColor || "#f7f7f3"); document.documentElement.style.setProperty("--ink", content.site.textColor || "#193a31"); document.documentElement.style.setProperty("--muted", content.site.mutedColor || "#65756f");
    if (!routeService) {
      const applyInternalFilters = () => { const queryValue = document.getElementById("internal-query").value.trim().toLocaleLowerCase("pt-BR"); const categoryValue = document.getElementById("internal-category").value; const audienceValue = document.getElementById("internal-audience").value; const departmentValue = document.getElementById("internal-department").value; const initialValue = document.getElementById("internal-initial").value; let visible = 0; document.querySelectorAll(".internal-static-card").forEach((card) => { const show = (categoryValue === "todos" || card.dataset.category === categoryValue) && (audienceValue === "todos" || card.dataset.audiences.split(" ").includes(audienceValue)) && (departmentValue === "todos" || card.dataset.department === departmentValue) && (initialValue === "todos" || card.dataset.initial === initialValue) && (!queryValue || card.dataset.title.includes(queryValue)); card.hidden = !show; if (show) visible += 1; }); document.getElementById("internal-count").textContent = `${visible} encontrado${visible === 1 ? "" : "s"}`; document.getElementById("internal-empty").hidden = visible !== 0; };
      ["internal-query", "internal-category", "internal-audience", "internal-department", "internal-initial"].forEach((id) => document.getElementById(id).addEventListener(id === "internal-query" ? "input" : "change", applyInternalFilters)); document.getElementById("internal-clear").addEventListener("click", () => { document.getElementById("internal-query").value = ""; document.getElementById("internal-category").value = routeCategory ? document.getElementById("internal-category").value : "todos"; document.getElementById("internal-audience").value = routeAudience || "todos"; document.getElementById("internal-department").value = "todos"; document.getElementById("internal-initial").value = "todos"; applyInternalFilters(); });
    }
    return;
  }

  root.innerHTML = page.segments.map(renderSegment).join("");
  const heroSlides = [...root.querySelectorAll(".hero-carousel>span")]; let heroSlideIndex = 0;
  if (heroSlides.length > 1 && !matchMedia("(prefers-reduced-motion: reduce)").matches) setInterval(() => { heroSlides[heroSlideIndex].classList.remove("active"); heroSlideIndex = (heroSlideIndex + 1) % heroSlides.length; heroSlides[heroSlideIndex].classList.add("active"); }, 6000);
  document.documentElement.style.setProperty("--green", content.site.primaryColor);
  document.documentElement.style.setProperty("--red", content.site.accentColor);
  document.documentElement.style.setProperty("--deep", content.site.deepColor || "#04392d");
  document.documentElement.style.setProperty("--cream", content.site.surfaceColor || "#f7f7f3");
  document.documentElement.style.setProperty("--ink", content.site.textColor || "#193a31");
  document.documentElement.style.setProperty("--muted", content.site.mutedColor || "#65756f");
  root.style.setProperty("--site-heading-font", fontStacks[siteDesign.headingFont || "lora"]);
  root.style.setProperty("--site-body-font", fontStacks[siteDesign.bodyFont || "source"]);

  function renderServices() {
    const normalized = query.trim().toLocaleLowerCase("pt-BR");
    const filtered = services.filter((service) => (audience === "todos" || service.audienceId === audience) && (category === "todos" || service.category === category) && (!normalized || `${service.title} ${service.department} ${service.category} ${service.destination}`.toLocaleLowerCase("pt-BR").includes(normalized)));
    document.getElementById("service-grid").innerHTML = filtered.map((service, index) => serviceCard(service, index)).join("");
    document.getElementById("result-count").textContent = `${filtered.length} encontrado${filtered.length === 1 ? "" : "s"}`;
    document.getElementById("results-title").textContent = audience !== "todos" ? `Serviços para ${audienceItems.find((item) => item.id === audience)?.label}` : category !== "todos" ? category : query ? "Resultado da busca" : text(segment("catalog"), "title", "Todos os serviços");
    document.getElementById("empty").hidden = filtered.length !== 0;
    document.getElementById("clear").hidden = audience === "todos" && category === "todos" && !query;
    document.querySelectorAll("[data-audience]").forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.audience === audience)));
    document.querySelectorAll("[data-category]").forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.category === category)));
  }
  const showResults = () => setTimeout(() => { const title = document.getElementById("results-title"); title?.focus({ preventScroll: true }); title?.scrollIntoView({ behavior: matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "start" }); }, 0);
  document.getElementById("service-search")?.addEventListener("input", (event) => { query = event.target.value; renderServices(); });
  document.getElementById("service-search")?.addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); showResults(); } });
  document.getElementById("service-search-form")?.addEventListener("submit", (event) => { event.preventDefault(); showResults(); });
  document.querySelectorAll("[data-shortcut]").forEach((button) => button.addEventListener("click", () => { query = button.dataset.shortcut; document.getElementById("service-search").value = query; audience = "todos"; category = "todos"; renderServices(); showResults(); }));
  document.querySelectorAll("[data-audience]").forEach((button) => button.addEventListener("click", () => { location.href = `?publico=${encodeURIComponent(button.dataset.audience)}`; }));
  document.querySelectorAll("[data-category]").forEach((button) => button.addEventListener("click", () => { location.href = `?categoria=${encodeURIComponent(slugify(button.dataset.category))}`; }));
  document.getElementById("clear")?.addEventListener("click", () => { audience = "todos"; category = "todos"; query = ""; document.getElementById("service-search").value = ""; renderServices(); showResults(); });
  const amandaLauncher = document.getElementById("amanda-launcher"); const amandaPanel = document.getElementById("amanda-panel");
  const amandaFocusable = () => [...(amandaPanel?.querySelectorAll('button:not([disabled]),a[href],textarea,input,select,[tabindex]:not([tabindex="-1"])') || [])];
  const trapAmandaFocus = (event) => { if (amandaPanel?.hidden) return; if (event.key === "Escape") { event.preventDefault(); toggleAmanda(false); return; } if (event.key !== "Tab") return; const controls = amandaFocusable(); if (!controls.length) return; const first = controls[0]; const last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  const toggleAmanda = (open) => { if (!amandaPanel) return; amandaPanel.hidden = !open; amandaLauncher?.setAttribute("aria-expanded", String(open)); if (open) requestAnimationFrame(() => amandaFocusable()[0]?.focus()); else amandaLauncher?.focus(); };
  const askAmanda = (question) => { const value = question.trim(); if (!value) return; document.getElementById("amanda-prompts").hidden = true; const transcript = document.getElementById("amanda-transcript"); transcript.insertAdjacentHTML("beforeend", `<article class="user"><small>Você</small><p>${escapeHtml(value)}</p></article><article><small>Amanda</small><p>Minha inteligência ainda está sendo preparada. Em breve vou responder e indicar o canal oficial mais adequado para você.</p></article>`); document.getElementById("amanda-input").value = ""; };
  amandaLauncher?.addEventListener("click", () => toggleAmanda(amandaPanel.hidden)); document.getElementById("amanda-close")?.addEventListener("click", () => toggleAmanda(false)); document.addEventListener("keydown", trapAmandaFocus);
  document.querySelectorAll("[data-amanda-prompt]").forEach((button) => button.addEventListener("click", () => askAmanda(button.dataset.amandaPrompt)));
  document.getElementById("amanda-form")?.addEventListener("submit", (event) => { event.preventDefault(); askAmanda(document.getElementById("amanda-input").value); });
  renderServices();
  const editorSelection = window.CENTRAL_EDITOR_SELECTION;
  if (editorSelection?.segmentId) {
    const selectedSegment = [...document.querySelectorAll("[data-editor-segment-id]")].find((element) => element.dataset.editorSegmentId === editorSelection.segmentId);
    selectedSegment?.classList.add("editor-selected-segment");
    const selectedItems = editorSelection.itemId ? [...document.querySelectorAll("[data-editor-item-id]")].filter((element) => element.dataset.editorItemId === editorSelection.itemId) : [];
    selectedItems.forEach((element) => element.classList.add("editor-selected-item"));
    if (selectedItems.length && selectedSegment?.id === "amanda-widget") toggleAmanda(true);
  }
})();
